version: "3.8"

services:
  banco-de-dados:
    image: mongo:5.0.3
    container_name: banco-de-dados-agenda-semanal
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data/mongoDB:/data/db
    ports:
      - "2002:27017"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-agenda-semanal
    restart: always
    environment:
      MONGO_DB_URI: "mongodb://root:root@banco-de-dados-agenda-semanal:27017"
      NOME_DB: "atividade"
      NOME_COLLECTION: "atividade"
      PORT: "2001"
      HOST_HTTP: "0.0.0.0"
    ports:
      - "2001:2001"

